var colours = ["purple", "green", "orange", "black", "white"];
document.getElementById("no-meth").innerHTML += "var colours = ['purple', 'green', 'orange', 'black', 'white'];<br>document.getElementById('no-meth').innerHTML = colours;<br>Output: " + colours;
var coloursTs = colours.toString();
console.log(coloursTs);
console.log(colours);
document.getElementById("to-string").innerHTML += "Converts an array to a string of comma separated values (original array unchanged):<br>var coloursTs = colours.toString();<br>Output: " + coloursTs;
var coloursJ = colours.join(" # ")
var coloursJs = colours.join(" and ")
document.getElementById("join").innerHTML += "Joins all array elements into a string and you can specify a seperator (original array unchanged):<br>var coloursJ = colours.join(' # ');<br>Output: " + coloursJ + "<br>join() with a string as the seperator:<br> var coloursJs = colours.join(' and ');<br>Output: " + coloursJs;
console.log(colours);
console.log(coloursJ);
console.log(coloursJs);
var coloursPop = colours.pop();
document.getElementById("pop").innerHTML += "Removes the last element from an array and returns that value (changes the length of original array):<br>var coloursPop = colours.pop();<br>Output: " + coloursPop;
console.log(colours);
console.log(coloursPop);
document.getElementById("new-arr").innerHTML = "The new array: " + colours;
document.getElementById("push").innerHTML += "Adds new elements to the end of an array and returns the new array length (changes the length of original array):<br>colours.push('pink');<br>Output: " + colours.push("pink");
document.getElementById("new-arr1").innerHTML = "The new array: " + colours;
console.log(colours);
var coloursShift = colours.shift();
document.getElementById("shift").innerHTML += "Removes the first array element and returns that value (changes the length of original array):<br>var coloursShift = colours.shift();<br>Output: " + coloursShift;
console.log(colours);
console.log(coloursShift);
document.getElementById("new-arr2").innerHTML = "The new array: " + colours;
document.getElementById("unshift").innerHTML += "Adds new elements to the beginning of an array and returns the new array length (changes the length of original array):<br>colours.unshift('violet');<br>Output: " + colours.unshift("violet");
document.getElementById("new-arr3").innerHTML = "The new array: " + colours;
console.log(colours);
var removedSplic = colours.splice(0, 2, "purple");
document.getElementById("splice").innerHTML += "Adds and removes items in an array and returns the removed items. To remove only, omit the third parameter. (Changes the original array):<br>var removedSplic = colours.splice(0, 2, 'purple'); (at position 0, remove 2 elements and add purple)<br>Output: " + removedSplic;
console.log(colours);
console.log(removedSplic);
document.getElementById("new-arr4").innerHTML = "The new array: " + colours;
var slic = colours.slice();
document.getElementById("slice").innerHTML += "Selects elements from an array and returns a new array (original array unchanged). Optional parameters specify elements to select (start and end index numbers as arguments), omit parameters to copy whole array:<br>var slic = colours.slice();<br>Output: " + slic;
var slicEnd = colours.slice(0, -1);
var slic1 = colours.slice(1);
console.log(slicEnd);
console.log(slic1);
document.getElementById("new-arr5").innerHTML = "slice() to copy all elements except the last:<br>var slicEnd = colours.slice(0, -1);<br>Output: " + slicEnd + "<br>slice() to copy elements from position 1:<br>var slic1 = colours.slice(1);<br>Output: " + slic1;
console.log(colours);
console.log(slic);
var newColours = ["red", "cyan"];
var cCat = colours.concat(newColours);
document.getElementById("concat").innerHTML += "Returns a new array by concatenating arrays (original array unchanged):";
document.getElementById("new-arr6").innerHTML = "colours array: " + colours + "<br>var newColours = ['red', 'cyan'];<br>var cCat = colours.concat(newColours);<br>New array after concatenating newColours to colours: " + cCat;
console.log(colours);
console.log(cCat);
colours = cCat;
console.log(colours);
colours[colours.length] = "grey";
document.getElementById("length").innerHTML += "Add a new element at the end of the array:<br>colours[colours.length] = 'grey';<br>The new array: " + colours;
console.log(colours);
delete colours[0];
document.getElementById("delete").innerHTML += "Deletes a property and it's value from an object (a JavaScript array is an object). The property can't be used until it is added again, this may leave holes in the array. It is recommended to use pop(), shift() or splice() to remove elements from an array instead. Returns true if the property is deleted, otherwise returns false.";
document.getElementById("new-arr7").innerHTML = "delete colours[0];<br>The new array: " + colours;
console.log(colours);
console.log(colours[0]);
//colours[0] = "";